Witcher.Beastiary.Web/Models/ErrorViewModel.cs
using System;

namespace Witcher.Beastiary.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Witcher.Beastiary.Web/Controllers/BeastController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Witcher.Beastiary.Core.Models;
using Witcher.Beastiary.Data.Interface;

namespace Witcher.Beastiary.Web.Controllers
{
    public class BeastController : Controller
    {
        private readonly IMonsterData _monsterData;

        public BeastController(IMonsterData monsterData)
        {
            _monsterData = monsterData;
        }

        public IActionResult Index(int id)
        {
            var model = _monsterData.GetSingle(id);
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var newBeast = new MonsterModel();
            return View(newBeast);
        }

        [HttpPost]
        public IActionResult Create(MonsterModel newMonster)
        {
            _monsterData.Create(newMonster);
            return RedirectToAction("Index", new { newMonster.Id });
        }

        [HttpGet]
        public IActionResult Edit(int id) 
        {
            var model = _monsterData.GetSingle(id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(MonsterModel updateMonster)
        {
            _monsterData.Update(updateMonster);
            return RedirectToAction("Index", new { updateMonster.Id });
        }

        public IActionResult Delete(int id)
        {
            _monsterData.Delete(id);
            return RedirectToAction("Index", "Beastiary");
        }
    }
}

Witcher.Beastiary.Web/Controllers/BeastiaryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Witcher.Beastiary.Data.Interface;

namespace Witcher.Beastiary.Web.Controllers
{
    public class BeastiaryController : Controller
    {
        private readonly IMonsterData _monsterData;

        public BeastiaryController(IMonsterData monsterData)
        {
            _monsterData = monsterData;
        }

        public IActionResult Index()
        {
            var model = _monsterData.GetAll();
            return View(model);
        }
    }
}

Witcher.Beastiary.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Witcher.Beastiary.Web.Models;

namespace Witcher.Beastiary.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Witcher.Beastiary.Web/Views/Beast/Create.cshtml
@using Witcher.Beastiary.Core.Models
@model MonsterModel

<h2>Hello World!</h2>

<form method="post">
    <div class="form-group">
        <label>Name</label>
        <input class="form-control col-6" type="text" asp-for="@Model.Name" required />
    </div>
    <div class="form-group">
        <label>Type</label>
        <select class="form-control col-6" asp-for="@Model.Type" asp-items="Html.GetEnumSelectList<MonsterType>()">

        </select>
    </div>
    <div class="form-group">
        <label>Description</label>
        <textarea class="form-control col-6" asp-for="@Model.Description"></textarea>
    </div>
    <div class="form-group">
        <label>Location</label>
        <input class="form-control col-6" type="text" asp-for="@Model.Location" required />
    </div>
    <div class="form-group">
        <label>Weakness</label>
        <input class="form-control col-6" type="text" asp-for="@Model.Weakness" />
    </div>

    <button type="submit" class="btn btn-outline-success">Save</button>

</form>

Witcher.Beastiary.Web/Views/Beast/Edit.cshtml
@using Witcher.Beastiary.Core.Models
@model MonsterModel

<h2>Hello World!</h2>

<form method="post">
    <div class="form-group">
        <label>Name</label>
        <input class="form-control col-6" type="text" asp-for="@Model.Name" required />
    </div>
    <div class="form-group">
        <label>Type</label>
        <select class="form-control col-6" asp-for="@Model.Type" asp-items="Html.GetEnumSelectList<MonsterType>()">
        </select>
    </div>
    <div class="form-group">
        <label>Description</label>
        <textarea class="form-control col-6" asp-for="@Model.Description"></textarea>
    </div>
    <div class="form-group">
        <label>Location</label>
        <input class="form-control col-6" type="text" asp-for="@Model.Location" required />
    </div>
    <div class="form-group">
        <label>Weakness</label>
        <input class="form-control col-6" type="text" asp-for="@Model.Weakness" />
    </div>

    <button type="submit" class="btn btn-outline-success">Save</button>

</form>

Witcher.Beastiary.Web/Views/Beast/Index.cshtml
@model Witcher.Beastiary.Core.Models.MonsterModel

<div class="jumbotron">
    <div class="row">
        <img src="https://via.placeholder.com/150" />
        <ul>
            <li><h6>@Model.Name</h6></li>
            <li><h6>@Model.Location</h6></li>
            <li><h6>@Model.Weakness</h6></li>
        </ul>
    </div>
    <div id="sub-menu" class="justify-content-center">
        <a class="btn btn-sm btn-outline-info" asp-controller="Beast" asp-action="Edit" asp-route-id="@Model.Id"><i class="far fa-edit"></i></a>
        <a class="btn btn-sm btn-outline-danger" asp-route-id="@Model.Id" data-toggle="modal" data-target="#deleteModal"><i class="far fa-trash-alt"></i></a>
        <a class="btn btn-sm btn-outline-primary" asp-controller="Beastiary" asp-action="Index"><i class="fas fa-list"></i></a>
    </div>

</div>

    <p>@Model.Description</p>

<partial name="_Delete" />

Witcher.Beastiary.Web/Views/Beastiary/Index.cshtml
@using Witcher.Beastiary.Core.Models
@model IEnumerable<MonsterModel>
@{
}
<h1>Beastiary</h1>

<a class="btn btn-sm btn-outline-primary" asp-controller="Beast" asp-action="Create">Add Beast</a>
<br />
<br />


<div>
    <h2>Beast</h2>
    <hr />
</div>
<div class="row">
    @foreach (var beast in Model)
    {
        @if (beast.Type == MonsterType.Beast)
        {
            <div class="card w-50">
                <div class="card-body">
                    <h3><a asp-controller="Beast" asp-action="Index" asp-route-id="@beast.Id">@beast.Name</a></h3>
                    <h6>@beast.Location</h6>
                </div>
            </div>
        }
    }

</div>

<div>
    <h2>Cursed Ones</h2>
    <hr />
</div>
<div class="row">
    @foreach (var cursedOnes in Model)
    {
        @if (cursedOnes.Type == MonsterType.Cursed_Ones)
        {
            <div class="card w-50">
                <div class="card-body">
                    <h3><a asp-controller="Beast" asp-action="Index" asp-route-id="@cursedOnes.Id">@cursedOnes.Name</a></h3>
                    <h6>@cursedOnes.Location</h6>
                </div>
            </div>
        }
    }

</div>

Witcher.Beastiary.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Witcher.Beastiary.Web/Views/Shared/_Delete.cshtml
@model Witcher.Beastiary.Core.Models.MonsterModel

<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Confirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete:</p>

                <p>Name: @Model.Name </p>
                <p>Location: @Model.Location</p>
            </div>
            <div class="modal-footer">
                <a class="btn btn-sm btn-outline-primary" asp-controller="Beast" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                <button type="button" class="btn btn-sm btn-outline-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Witcher.Beastiary.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Witcher.Beastiary.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/Beast.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Witcher.Beastiary.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Beastiary" asp-action="Index">Beastiary</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Witcher.Beastiary.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>